name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '2.7'

    - name: Install pynt
      run: |
        pip install setuptools wheel
        pip install pynt

    - name: Build Release
      id: build_release
      run: python build.py github_actions_release

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ steps.build_release.outputs.version }}
        body: |
          ## WoT Version

          ## Changelog
          -
          ## Downloads
          - `${{ steps.build_release.outputs.release_name }}`: Mod with its dependencies (recommended)
          - `${{ steps.build_release.outputs.wotmod_name }}`: Single `.wotmod` file. Dependecies need to be downloaded separately.
        files: |
          ${{ steps.build_release.outputs.wotmod_path }}
          ${{ steps.build_release.outputs.release_path }}
